name: Build Base PHP Containers and deploy to registry

on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2", "8.3"]
        target: [production, development]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            osuwams/php
            ghcr.io/osu-wams/php
          tags: |
            type=ref,event=branch
            type=raw,value=${{ matrix.version }}-apache${{ matrix.target == 'development' && '-dev' || '' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.version }}
          push: ${{ github.event_name != 'pull_request' }}
          target: ${{ matrix.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
